test_that("posterior_plot throws an error for invalid cis values", {
  data("ts_data")
  data1 <- subset(ts_data, id == "ID1")
  data1 <- subset(data1, select = -c(id))
  fitobj <- BGGM::var_estimate(data1)
  cis <- c(0.8, 0.9, 1.5)
  expect_error(posterior_plot(fitobj, cis = cis))
  cis <- c(0, 0.9, 0.95)
  expect_error(posterior_plot(fitobj, cis = cis))
})
