// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4VAR_LKJ_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4VAR_LKJ_beep_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4VAR_wishart_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4VAR_wishart_beep_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4test_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4VAR_LKJ_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4VAR_LKJ_mod, 0},
    {"_rcpp_module_boot_stan_fit4VAR_LKJ_beep_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4VAR_LKJ_beep_mod, 0},
    {"_rcpp_module_boot_stan_fit4VAR_wishart_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4VAR_wishart_mod, 0},
    {"_rcpp_module_boot_stan_fit4VAR_wishart_beep_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4VAR_wishart_beep_mod, 0},
    {"_rcpp_module_boot_stan_fit4test_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4test_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsnet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
