#' Simulated Time Series Dataset
#'
#' This dataset contains a simulated time series dataset for two individuals
#' generated using the graphicalVAR package.
#'
#' @format ## `ts_data`
#' A data frame with 500 rows and 7 columns.
#' @source Simulated using the [graphicalVAR::graphicalVARsim()] function.
#'
#' @usage data(ts_data)
#'
#' @details
#' The dataset consists of 250 observations each of 6 variables for two individuals.
#' The variables V1-V6 represent simulated time series data generated using the graphicalVARsim function from the graphicalVAR package.
#' The 'id' column contains a character string as identifier of the two individuals.
#' The data have been standardized  to have zero mean and unit variance.
#'
#'
#' @keywords dataset
"ts_data"



#' Example Posterior Samples
#'
#' This dataset contains posterior samples of beta coefficients and partial correlations for two individuals.
#' It was generated by fitting a GVAR model using [stan_gvar()] with three variables from the [ts_data] dataset.
#'
#' @format ## `fit_data`
#' A list with two elements, each containing posterior samples for one individual.
#'
#' @usage data(fit_data)
#'
#' @source The data is generated using the [stan_gvar()] function on subsets
#' of the [ts_data] time series data.
#'
#' @details
#' The list contains two elements, each containing posterior samples for one individual.
#' The samples were extracted using the [stan_fit_convert()] function.
#' For each individual, the list elements contain the posterior means of the beta coefficients
#' ("beta_mu") and the posterior means of the partial correlations ("pcor_mu").
#' The "fit" element contains all 1000 posterior samples of the beta coefficients and partial correlations.
#'
#'
#' @keywords dataset
"fit_data"

